import type { AgentReport } from "@/lib/agent-workflows";
const titles: Record<string, string> = { identity: "What this token represents", reference: "Issuer price reference", venue: "Where it trades", activity: "Trading activity", events: "Recent issuer events", alerts: "Your monitoring evidence", policy: "Previous safety checks", briefing: "Research summary", model_answer: "Analyst explanation" };
export function ReportSummary({ report }: { report: AgentReport }) {
  const groups = new Map<string, typeof report.claims>();
  for (const claim of report.claims) {
    const category = claim.category || "briefing";
    groups.set(category, [...(groups.get(category) || []), claim]);
  }
  return <article className="agent-report"><div className="report-heading"><h3>{report.kind === "unsupported" ? "This question is outside the available research" : "Your asset briefing"}</h3><time dateTime={report.generatedAt}>{new Date(report.generatedAt).toLocaleString("en-US", { timeZone: "UTC" })} UTC</time></div><div className="report-sections">{[...groups].map(([category, claims]) => <section className="report-section" key={category}><h4>{titles[category] || "Research summary"}</h4>{claims.map((claim, index) => <div className="report-claim" key={index}><p>{claim.text}</p><div className="claim-citations">{claim.citations.map((id) => { const citation = report.citations.find((item) => item.id === id); return citation ? <a key={id} href={citation.url} target="_blank" rel="noopener noreferrer" aria-label={`Source ${id}: ${citation.label}`}>[{id}] {citation.label} / {citation.state}</a> : null; })}</div></div>)}</section>)}</div>{report.unknowns.length ? <section className="report-unknowns"><h4>What we cannot confirm</h4><ul>{report.unknowns.map((unknown) => <li key={unknown}>{unknown}</li>)}</ul></section> : null}<details className="source-details"><summary>Sources, units, and observation times ({report.citations.length})</summary>{report.citations.map((citation) => <div className="report-source" key={citation.id}><a href={citation.url} target="_blank" rel="noopener noreferrer">[{citation.id}] {citation.label}</a><span className="status-badge status-review">{citation.state}</span><p>{citation.unit}</p><p className="cell-meta">Observed: {citation.observedAt || "Source time unknown"}<br />Retrieved: {citation.retrievedAt}</p></div>)}<p className="cell-meta">Report version {report.version} / evidence {report.evidenceHash}</p>{report.model ? <p className="cell-meta">Model: {report.model} / prompt {report.promptVersion} / cost {report.usage?.costUsd ?? "Unavailable"} USD</p> : <p className="cell-meta">Generated from source records without a language model.</p>}</details></article>;
}
