import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { network } from "hardhat";
import { createPublicClient, createWalletClient, custom, erc20Abi, http, keccak256, pad, type Abi, type Address, type Hex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { compileContracts } from "./compile-contracts.mjs";
import { prepareTestnetTrade, type TestnetManifest } from "../src/lib/testnet-execution";
import { reconcileLogs } from "../src/lib/receipt-verification";
import { sourcedAsset, contract } from "../tests/source-fixtures";
import type { PolicyEvidence } from "../src/lib/policy";
import { readDemoStatus } from "../src/lib/demo-status";

const url = process.env.ARBITRUM_SEPOLIA_RPC_URL || "https://sepolia-rollup.arbitrum.io/rpc";
const source = createPublicClient({ transport: http(url, { timeout: 15000, retryCount: 0 }) });
assert.equal(await source.getChainId(), 421614);
const blockNumber = await source.getBlockNumber();
const connection = await network.create({ network: "arbitrumDemo", override: { forking: { url, blockNumber: Number(blockNumber) } } });
try {
  await connection.provider.request({ method: "evm_mine" });
  const transport = custom(connection.provider);
  const client = createPublicClient({ transport });
  const wallet = createWalletClient({ transport });
  const [owner, stranger] = await wallet.getAddresses();
  const signerKey = `0x${"42".repeat(32)}` as Hex;
  const contracts = compileContracts() as Record<string, Record<string, { abi: Abi; evm: { bytecode: { object: string } } }>>;
  const artifact = Object.values(contracts).map((entry) => entry.TestnetDemo).find(Boolean)!;
  const router = "0x101F443B4d1b059569D643917553c771E1b9663E";
  const factory = "0x248AB79Bbb9bC29bB72f7Cd42F17e054Fc40188e";
  const quoter = "0x2779a0CC1c3e0E44D2542EC3e79e3864Ae93Ef0B";
  const hash = await wallet.deployContract({ account: owner, chain: null, abi: artifact.abi, bytecode: `0x${artifact.evm.bytecode.object}`, args: [owner, privateKeyToAccount(signerKey).address, router, factory] });
  const deployment = await client.waitForTransactionReceipt({ hash });
  assert.equal(deployment.status, "success");
  const controller = deployment.contractAddress!;
  await assert.rejects(client.simulateContract({ account: stranger, address: controller, abi: artifact.abi, functionName: "activate" }));
  const activate = await wallet.writeContract({ account: owner, chain: null, address: controller, abi: artifact.abi, functionName: "activate" });
  assert.equal((await client.waitForTransactionReceipt({ hash: activate })).status, "success");
  const read = (functionName: string) => client.readContract({ address: controller, abi: artifact.abi, functionName }) as Promise<Address>;
  const [executor, stablecoin, stock, sequencer, adapter, pool, stableFeed, stockFeed] = await Promise.all(["executor", "stablecoin", "stock", "sequencer", "adapter", "pool", "stableFeed", "stockFeed"].map(read));
  const binding = async (address: Address) => ({ address, codeHash: keccak256((await client.getCode({ address }))!), sourceUrl: `https://sepolia.arbiscan.io/address/${address}` });
  const manifest: TestnetManifest = { chainId: 421614, demo: { controller: await binding(controller) }, executor: await binding(executor), stablecoin: await binding(stablecoin), sequencer: await binding(sequencer), assets: [{ symbol: "AAPL", assetKey: `robinhood:4663:${contract.toLowerCase()}`, token: await binding(stock), protocol: 3, adapter: await binding(adapter), venue: await binding(router), factory: await binding(factory), quoter: await binding(quoter), poolId: pad(pool), fee: 3000, tickSpacing: 0, oracles: [{ token: stablecoin, feed: await binding(stableFeed), maxAge: 3600 }, { token: stock, feed: await binding(stockFeed), maxAge: 3600 }] }] };
  assert.equal((await readDemoStatus(manifest, transport)).state, "ready");
  const unfunded = await prepareTestnetTrade(manifest, structuredClone(sourcedAsset), "buy", "5000000", stranger, { transport, signerKey, persist: async () => {} });
  assert.equal(unfunded.approval, null);
  assert.equal(unfunded.transaction, null);
  assert.match(unfunded.message, /does not have enough demo tokens/);
  let evidence: PolicyEvidence;
  const prepare = async (direction: "buy" | "sell", inputAmount: string) => {
    const now = new Date(Number((await client.getBlock()).timestamp) * 1000);
    return prepareTestnetTrade(manifest, structuredClone(sourcedAsset), direction, inputAmount, owner, { transport, signerKey, now: () => now, persist: async (value) => { evidence = value; } });
  };
  const results = [];
  for (const [direction, amount, input, output] of [["buy", "5000000", stablecoin, stock], ["sell", "10000000000000000", stock, stablecoin]] as const) {
    const approval = await wallet.writeContract({ account: owner, chain: null, address: input, abi: erc20Abi, functionName: "approve", args: [executor, BigInt(amount)] });
    assert.equal((await client.waitForTransactionReceipt({ hash: approval })).status, "success");
    const before = await client.readContract({ address: output, abi: erc20Abi, functionName: "balanceOf", args: [owner] });
    const prepared = await prepare(direction, amount);
    assert.equal(prepared.decision.status, "eligible");
    assert.ok(prepared.transaction);
    const sent = await wallet.sendTransaction({ account: owner, chain: null, to: executor, data: prepared.transaction.data, gas: BigInt(prepared.transaction.gas) + BigInt(100000) });
    const receipt = await client.waitForTransactionReceipt({ hash: sent });
    assert.equal(receipt.status, "success");
    const received = reconcileLogs(receipt.logs, executor, owner, evidence!.testnet ? prepared.decision.evidenceHash : "", input, output, amount);
    assert.ok(received);
    const after = await client.readContract({ address: output, abi: erc20Abi, functionName: "balanceOf", args: [owner] });
    assert.equal(after - before, BigInt(received));
    await assert.rejects(client.call({ account: owner, to: executor, data: prepared.transaction.data }));
    results.push({ direction, output: received, reconciled: true });
  }
  await connection.provider.request({ method: "evm_increaseTime", params: [3601] });
  await connection.provider.request({ method: "evm_mine" });
  const stale = await prepare("buy", "5000000");
  assert.equal(stale.decision.status, "blocked");
  assert.equal(stale.transaction, null);
  assert.equal((await readDemoStatus(manifest, transport)).state, "stale");
  await assert.rejects(client.simulateContract({ account: stranger, address: controller, abi: artifact.abi, functionName: "refreshFeeds" }));
  const refresh = await wallet.writeContract({ account: owner, chain: null, address: controller, abi: artifact.abi, functionName: "refreshFeeds" });
  assert.equal((await client.waitForTransactionReceipt({ hash: refresh })).status, "success");
  assert.ok((await prepare("buy", "5000000")).approval);
  assert.equal((await readDemoStatus(manifest, transport)).state, "ready");
  const evidenceRecord = { kind: "Local fork of Arbitrum Sepolia, not public deployment", sourceBlock: blockNumber.toString(), ownerOnlyActivation: true, ownerOnlyRefresh: true, unfundedWallet: "blocked without approval", replay: "rejected", staleFeeds: "blocked and restored by owner refresh", results, deploymentGas: deployment.gasUsed.toString() };
  await mkdir("artifacts", { recursive: true });
  await writeFile("artifacts/testnet-demo-fork.json", JSON.stringify(evidenceRecord, null, 2));
  console.log(JSON.stringify(evidenceRecord));
} finally { await connection.close(); }
